name: build_image
on:
  push:
    branches: ["master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: p4acr
          repository: p4acr.azurecr.io
          image: p4moocp4
          #git_access_token: ${{ secrets.git_access_token }}
          folder: .
          dockerfile: ./Dockerfile
          branch: master
          #build_args: '[{"arg_one":"value_one"}, {"arg_two":"value_two"}]'